rest:
  swagger-open: true #是否开启swagger (true/false)
  auth-open: true #jwt鉴权机制是否开启(true或者false)
  sign-open: false #签名机制是否开启(true或false)

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key
  white: cloudware/*

server:
  port: 8081 #项目端口

mybatis-plus:
  mapper-locations: classpath*:com/cuiyun/kfcoding/rest/**/mapping/*.xml
  typeAliasesPackage: com.cuiyun.kfcoding.rest.modular.*.model
  typeEnumsPackage: com.cuiyun.kfcoding.rest.modular.*.enums
  sqlSessionFactory:
  global-config:
    id-type: 3  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector #逻辑删除
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/kfcoding?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 1234
      filters: log4j,wall,mergeStat
      driver-class-name: com.mysql.jdbc.Driver

logging:
  level.root: info
  level.com.cuiyun: debug
  path: logs/
  file: kfcoding-rest.log